import { cn } from "@/shared/lib/utils"
import { queryClient } from "@/shared/queryClient"
import { QueryClientProvider } from "@tanstack/react-query"
import type { Metadata } from "next"
import { pretendard } from "./fonts/fonts"
import "./globals.css"
import { Toaster } from "@/shared/ui/sonner"

export const metadata: Metadata = {
  title: "mmm",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn("", pretendard.variable)}>

        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
        <Toaster position='top-center' />
      </body>
    </html>
  )
}
